# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResearchKitPOC' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for ResearchKitPOC

pod 'ResearchKit', '~> 1.0'

target 'ResearchKitPOCTests' do
inherit! :search_paths
# Pods for testing
end

end
